name: beta-build

on:
  create:
    tags:
      - '*-beta*'
    branches: [beat]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Flutter Dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - name: Env Init
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks
#          echo "${{ secrets.PLAY_JSON }}" | base64 --decode > android/play.json
      - name: APK Build
        run:  flutter build apk --obfuscate --split-per-abi --split-debug-info=./info
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks
      - name: AAB Build
        run: flutter build appbundle --obfuscate --split-debug-info=./info
      - name: Push AAB/APK Github Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
